version: "3.7"

services:

  flask:
    build: ./flask_web_app
    container_name: flask
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 8080
    links:
      - mongo

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
  
  mongo:
    image: mongo
    hostname: mongo
    ports:
      - 27017:27017
    depends_on:
      - mongo-express

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081