version: '3.1'

services:
  mongo:
    image: 'mongo'
    ports:
      - '27017:27017'
    depends_on:
      - 'mongo-express'

  app:
    tty: true
    stdin_open: true
    depends_on:
      - 'mongo'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - MONGO_URL=mongodb://mongo:27017/News_feed

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
